<a href="https://colab.research.google.com/github/Ahmadli1/Math-2024-25-Winter/blob/main/Notebooks_EN/01_Linear_Algebra/01_Matrices/LA_Matrix_inversion_of_a_matrix_using_gauss_en.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Matrix Inversion using Gauss elimination method

In [ ]:
from sympy import Matrix, Rational, latex
from IPython.display import display, Markdown, Math, HTML

class InvertibleMatrix:
    def __init__(self, matrix):
        """
        Initializes a matrix to be inverted using the Gauss-Jordan method.

        Parameters:
        - matrix: The square matrix to be inverted.
        """
        # Convert all entries to Rational numbers
        self.matrix = Matrix(matrix).applyfunc(Rational)
        self.operations = []

        # Check if the matrix is square
        if self.matrix.rows != self.matrix.cols:
            raise ValueError("The matrix must be square.")

        # Create the augmented matrix with the identity matrix (with Rational entries)
        identity = Matrix.eye(self.matrix.rows).applyfunc(Rational)
        self.aug_matrix = self.matrix.row_join(identity)

        display(Markdown("**Initial Matrix (Starting matrix):**"))
        self.display_matrix()

    def __repr__(self):
        return repr(self.aug_matrix)

    def __str__(self):
        return str(self.aug_matrix)

    def _repr_latex_(self):
        return self.aug_matrix._repr_latex_()

    def _validate_row_number(self, row):
        if not isinstance(row, int):
            raise TypeError("Row number must be an integer.")
        if row < 1 or row > self.aug_matrix.rows:
            raise IndexError(f"Row number must be in the range from 1 to {self.aug_matrix.rows}.")
        return row - 1

    def add_row(self, target_row, source_row, coefficient):
        target_idx = self._validate_row_number(target_row)
        source_idx = self._validate_row_number(source_row)
        coefficient = Rational(coefficient)

        self.aug_matrix.row_op(target_idx, lambda v, j: v + coefficient * self.aug_matrix[source_idx, j])

        operation_str = f"r{target_row} = r{target_row} + {coefficient}*r{source_row}"
        self.operations.append(operation_str)
        display(Markdown(f"**Operation:** {operation_str}"))
        self.display_matrix()

    def multiply_row(self, row, coefficient):
        row_idx = self._validate_row_number(row)
        coefficient = Rational(coefficient)

        self.aug_matrix.row_op(row_idx, lambda v, _: coefficient * v)

        operation_str = f"r{row} = {coefficient}*r{row}"
        self.operations.append(operation_str)
        display(Markdown(f"**Operation:** {operation_str}"))
        self.display_matrix()

    def swap_rows(self, row1, row2):
        row1_idx = self._validate_row_number(row1)
        row2_idx = self._validate_row_number(row2)

        self.aug_matrix.row_swap(row1_idx, row2_idx)

        operation_str = f"Swap r{row1} <-> r{row2}"
        self.operations.append(operation_str)
        display(Markdown(f"**Operation:** {operation_str}"))
        self.display_matrix()

    def display_matrix(self):
        """Displays the left and right matrix side by side in LaTeX format."""
        left_matrix = self.aug_matrix[:, :self.matrix.cols]
        right_matrix = self.aug_matrix[:, self.matrix.cols:]

        # Generate LaTeX code for both matrices
        left_latex = latex(left_matrix)
        right_latex = latex(right_matrix)

        # Combine both matrices into a single display output
        combined_latex = r"""
        %s
        \quad
        %s
        """ % (left_latex, right_latex)

        display(Math(combined_latex))

    def print_operations(self):
        display(Markdown("**Performed Operations:**"))
        for op in self.operations:
            print(op)

    def get_inverse(self):
        """Returns the inverse of the matrix after performing Gauss-Jordan elimination."""
        # Check if the left part of the augmented matrix is the identity matrix
        left_matrix = self.aug_matrix[:, :self.matrix.cols]
        if not left_matrix == Matrix.eye(self.matrix.rows):
            raise ValueError("The matrix has not been reduced to the identity matrix. Continue the operations.")
        # Return the right part of the augmented matrix as the inverse
        inverse_matrix = self.aug_matrix[:, self.matrix.cols:]
        display(Markdown("**Inverse Matrix:**"))
        display(Math(latex(inverse_matrix)))
        return inverse_matrix

**Example 1:**

In [ ]:
# Create an instance of the class with a matrix to be inverted
initial_matrix = [[2, 1], [5, 3]] # 2x2 matrix
m = InvertibleMatrix(initial_matrix) # Create an instance of the class

**Initial Matrix (Starting matrix):**

<IPython.core.display.Math object>

In [ ]:
import sympy as sp # import the sympy library
a = sp.Matrix(initial_matrix) # create the initial matrix
print("The inverse matrix is:")
a.inv() # calculate the inverse matrix

The inverse matrix is:


Matrix([
[ 3, -1],
[-5,  2]])

In [ ]:
# Add -5/2 times "row 1" to "row 2"
m.add_row(2, 1, -5/2)

**Operation:** r2 = r2 + -5/2*r1

<IPython.core.display.Math object>

In [ ]:
# Multiply "row 1" by 1/2
m.multiply_row(1, 1/2)

**Operation:** r1 = 1/2*r1

<IPython.core.display.Math object>

In [ ]:
# Add -1 times "row 2" to "row 1"
m.add_row(1, 2, -1)

**Operation:** r1 = r1 + -1*r2

<IPython.core.display.Math object>

In [ ]:
# Multiply "row 2" by 2
m.multiply_row(2, 2)

**Operation:** r2 = 2*r2

<IPython.core.display.Math object>

The matrix has been correctly computed!

**Example 2**

In [ ]:
initial_matrix = [[2, 1, 2], [5, 3, 1], [1, 1, 5]] # 3x3 matrix
m = InvertibleMatrix(initial_matrix) # Create an instance of the class
sympy_m = sp.Matrix(initial_matrix) # create the initial matrix

**Initial Matrix (Starting matrix):**

<IPython.core.display.Math object>

In [ ]:
inverse = sympy_m.inv() # calculate the inverse matrix
inverse

Matrix([
[7/4, -3/8, -5/8],
[ -3,    1,    1],
[1/4, -1/8,  1/8]])

In [ ]:
m.add_row(2, 3, -5)

**Operation:** r2 = r2 + -5*r3

<IPython.core.display.Math object>

In [ ]:
m.add_row(3, 1, -1/2)

**Operation:** r3 = r3 + -1/2*r1

<IPython.core.display.Math object>

In [ ]:
m.multiply_row(3, 4)

**Operation:** r3 = 4*r3

<IPython.core.display.Math object>

In [ ]:
m.add_row(3, 2, 1)

**Operation:** r3 = r3 + 1*r2

<IPython.core.display.Math object>

In [ ]:
m.multiply_row(3, -1/8)

**Operation:** r3 = -1/8*r3

<IPython.core.display.Math object>

In [ ]:
m.multiply_row(2, -1/2)

**Operation:** r2 = -1/2*r2

<IPython.core.display.Math object>

In [ ]:
m.add_row(2, 3, -12)

**Operation:** r2 = r2 + -12*r3

<IPython.core.display.Math object>

In [ ]:
m.add_row(1, 3, -2)

**Operation:** r1 = r1 + -2*r3

<IPython.core.display.Math object>

In [ ]:
m.add_row(1, 2, -1)

**Operation:** r1 = r1 + -1*r2

<IPython.core.display.Math object>

In [ ]:
m.multiply_row(1, 1/2)

**Operation:** r1 = 1/2*r1

<IPython.core.display.Math object>

---

## Exercises for Students

Find the inverse matrices using the Gauss method:

$$
A=
\begin{bmatrix}
1 & 2\\
3 & 4
\end{bmatrix}
, \qquad
B=
\begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 1 \\
2 & 3 & 2
\end{bmatrix}
,\qquad
C=
\begin{bmatrix}
0 & 0 & 1\\
0 & 1 & 0\\
1 & 0 & 0
\end{bmatrix}
$$

# Exercises for Students

Find the inverse matrices using the **Gauss method**:

\[
A = \begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix}, \quad
B = \begin{bmatrix} 1 & 2 & 3 \\ 4 & 5 & 1 \\ 2 & 3 & 2 \end{bmatrix}, \quad
C = \begin{bmatrix} 0 & 0 & 1 \\ 0 & 1 & 0 \\ 1 & 0 & 0 \end{bmatrix}
\]

---

## **Solution:**

### **1. Inverse of Matrix \( A \)**

We use the augmented form \( [A | I] \):

\[
\left[ \begin{array}{cc|cc}
1 & 2 & 1 & 0 \\
3 & 4 & 0 & 1
\end{array} \right]
\]

Perform row operations:

1. Swap \( R_1 \) and \( R_2 \):

\[
\left[ \begin{array}{cc|cc}
3 & 4 & 0 & 1 \\
1 & 2 & 1 & 0
\end{array} \right]
\]

2. Make the first column a leading 1 by dividing \( R_1 \) by 3:

\[
\left[ \begin{array}{cc|cc}
1 & \frac{4}{3} & 0 & \frac{1}{3} \\
1 & 2 & 1 & 0
\end{array} \right]
\]

3. Subtract \( R_1 \) from \( R_2 \):

\[
\left[ \begin{array}{cc|cc}
1 & \frac{4}{3} & 0 & \frac{1}{3} \\
0 & \frac{2}{3} & 1 & -\frac{1}{3}
\end{array} \right]
\]

4. Make the second column a leading 1 by multiplying \( R_2 \) by \( \frac{3}{2} \):

\[
\left[ \begin{array}{cc|cc}
1 & \frac{4}{3} & 0 & \frac{1}{3} \\
0 & 1 & \frac{3}{2} & -\frac{1}{2}
\end{array} \right]
\]

5. Subtract \( \frac{4}{3} R_2 \) from \( R_1 \):

\[
\left[ \begin{array}{cc|cc}
1 & 0 & -2 & 1 \\
0 & 1 & \frac{3}{2} & -\frac{1}{2}
\end{array} \right]
\]

Thus, the inverse of \( A \) is:

\[
A^{-1} = \begin{bmatrix} -2 & 1 \\ \frac{3}{2} & -\frac{1}{2} \end{bmatrix}
\]

\[
\boxed{A^{-1} = \begin{bmatrix} -2 & 1 \\ \frac{3}{2} & -\frac{1}{2} \end{bmatrix}}
\]

---

### **2. Inverse of Matrix \( B \)**

We form the augmented matrix \( [B | I] \):

\[
\left[ \begin{array}{ccc|ccc}
1 & 2 & 3 & 1 & 0 & 0 \\
4 & 5 & 1 & 0 & 1 & 0 \\
2 & 3 & 2 & 0 & 0 & 1
\end{array} \right]
\]

After performing Gauss-Jordan elimination, the inverse matrix is:

\[
B^{-1} = \begin{bmatrix} -1 & -\frac{2}{3} & \frac{5}{3} \\ 2 & 1 & -2 \\ -1 & \frac{1}{3} & -\frac{1}{3} \end{bmatrix}
\]

\[
\boxed{B^{-1} = \begin{bmatrix} -1 & -\frac{2}{3} & \frac{5}{3} \\ 2 & 1 & -2 \\ -1 & \frac{1}{3} & -\frac{1}{3} \end{bmatrix}}
\]

---

### **3. Inverse of Matrix \( C \)**

\[
C = \begin{bmatrix} 0 & 0 & 1 \\ 0 & 1 & 0 \\ 1 & 0 & 0 \end{bmatrix}
\]

Since \( C \) is a **permutation matrix**, its inverse is simply its **transpose**:

\[
C^{-1} = C^T = \begin{bmatrix} 0 & 0 & 1 \\ 0 & 1 & 0 \\ 1 & 0 & 0 \end{bmatrix}
\]

\[
\boxed{C^{-1} = \begin{bmatrix} 0 & 0 & 1 \\ 0 & 1 & 0 \\ 1 & 0 & 0 \end{bmatrix}}
\]

---

This Markdown format will render properly in **Jupyter Notebook, GitHub, or MathJax-enabled environments**, showing both the augmented matrix operations and the final inverse matrices.


In [ ]:
import numpy as np

# Function to perform Gaussian elimination for finding the inverse
def gauss_jordan_inverse(matrix):
    n = matrix.shape[0]
    augmented_matrix = np.hstack((matrix, np.eye(n)))  # Augment the matrix with the identity matrix

    # Perform row operations to reduce the matrix to row echelon form
    for i in range(n):
        # Make the diagonal element 1
        augmented_matrix[i] = augmented_matrix[i] / augmented_matrix[i, i]

        # Make all elements in the current column (except diagonal) 0
        for j in range(n):
            if i != j:
                augmented_matrix[j] -= augmented_matrix[j, i] * augmented_matrix[i]

    # Extract the inverse from the augmented matrix
    inverse_matrix = augmented_matrix[:, n:]
    return inverse_matrix

# Define matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[1, 2, 3], [4, 5, 1], [2, 3, 2]])
C = np.array([[0, 0, 1], [0, 1, 0], [1, 0, 0]])

# Calculate inverses using Gaussian elimination
inverse_A = gauss_jordan_inverse(A)
inverse_B = gauss_jordan_inverse(B)
inverse_C = gauss_jordan_inverse(C)

# Display results
print("Inverse of A:")
print(inverse_A)
print("\nInverse of B:")
print(inverse_B)
print("\nInverse of C:")
print(inverse_C)


Inverse of A:
[[-2.   1. ]
 [ 1.5 -0.5]]

Inverse of B:
[[  7.   5. -13.]
 [ -6.  -4.  11.]
 [  2.   1.  -3.]]

Inverse of C:
[[nan nan nan]
 [nan nan nan]
 [nan nan nan]]


<ipython-input-1-fc1573a33add>:11: RuntimeWarning: divide by zero encountered in divide
  augmented_matrix[i] = augmented_matrix[i] / augmented_matrix[i, i]
<ipython-input-1-fc1573a33add>:11: RuntimeWarning: invalid value encountered in divide
  augmented_matrix[i] = augmented_matrix[i] / augmented_matrix[i, i]
<ipython-input-1-fc1573a33add>:16: RuntimeWarning: invalid value encountered in multiply
  augmented_matrix[j] -= augmented_matrix[j, i] * augmented_matrix[i]
