<a href="https://colab.research.google.com/github/Ahmadli1/Math-2024-25-Winter/blob/main/Notebooks_EN/01_Linear_Algebra/01_Matrices/LA_Matrix_triangular_en.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Triangular Matrices and determinant calculation

In [ ]:
import sympy as sp
from sympy import Matrix, symbols, Rational
from IPython.display import display, Markdown

class SymbolicMatrix:
    def __init__(self, matrix):
        self.matrix = Matrix(matrix).applyfunc(Rational)
        self.operations = []
        display(Markdown("**Initial Matrix:**"))
        display(self.matrix)  # Display the matrix upon initialization

    def __repr__(self):
        return repr(self.matrix)  # Use Matrix's repr

    def __str__(self):
        return str(self.matrix)  # Use Matrix's str

    def _repr_latex_(self):
        return self.matrix._repr_latex_()  # Delegate LaTeX display

    def _validate_row_number(self, row):
        if not isinstance(row, int):
            raise TypeError("Row number must be an integer.")
        if row < 1 or row > self.matrix.rows:
            raise IndexError(f"Row number must be in the range from 1 to {self.matrix.rows}.")
        return row - 1

    def _validate_col_number(self, col):
        if not isinstance(col, int):
            raise TypeError("Column number must be an integer.")
        if col < 1 or col > self.matrix.cols:
            raise IndexError(f"Column number must be in the range from 1 to {self.matrix.cols}.")
        return col - 1

    # Row operations
    def add_row(self, target_row, source_row, coefficient):
        target_idx = self._validate_row_number(target_row)
        source_idx = self._validate_row_number(source_row)
        coefficient = Rational(coefficient)

        self.matrix.row_op(target_idx, lambda v, j: v + coefficient * self.matrix[source_idx, j])
        operation_str = f"r{target_row} = r{target_row} + {coefficient}*r{source_row}"
        self.operations.append(operation_str)
        display(Markdown(f"**Operation:** {operation_str}"))
        display(self.matrix)

    def multiply_row(self, row, coefficient):
        row_idx = self._validate_row_number(row)
        coefficient = Rational(coefficient)
        self.matrix.row_op(row_idx, lambda v, _: coefficient * v)
        operation_str = f"r{row} = {coefficient}*r{row}"
        self.operations.append(operation_str)
        display(Markdown(f"**Operation:** {operation_str}"))
        display(self.matrix)

    def swap_rows(self, row1, row2):
        row1_idx = self._validate_row_number(row1)
        row2_idx = self._validate_row_number(row2)
        self.matrix.row_swap(row1_idx, row2_idx)
        operation_str = f"Swap r{row1} <-> r{row2}"
        self.operations.append(operation_str)
        display(Markdown(f"**Operation:** {operation_str}"))
        display(self.matrix)

    # Column operations
    def add_col(self, target_col, source_col, coefficient):
        target_idx = self._validate_col_number(target_col)
        source_idx = self._validate_col_number(source_col)
        self.matrix.col_op(target_idx, lambda v, i: v + coefficient * self.matrix[i, source_idx])
        operation_str = f"c{target_col} = c{target_col} + {coefficient}*c{source_col}"
        self.operations.append(operation_str)
        display(Markdown(f"**Operation:** {operation_str}"))
        display(self.matrix)

    def multiply_col(self, col, coefficient):
        col_idx = self._validate_col_number(col)
        self.matrix.col_op(col_idx, lambda v, _: coefficient * v)
        operation_str = f"c{col} = {coefficient}*c{col}"
        self.operations.append(operation_str)
        display(Markdown(f"**Operation:** {operation_str}"))
        display(self.matrix)

    def swap_cols(self, col1, col2):
        col1_idx = self._validate_col_number(col1)
        col2_idx = self._validate_col_number(col2)
        self.matrix.col_swap(col1_idx, col2_idx)
        operation_str = f"Swap c{col1} <-> c{col2}"
        self.operations.append(operation_str)
        display(Markdown(f"**Operation:** {operation_str}"))
        display(self.matrix)

    # Display the operations performed
    def print_operations(self):
        display(Markdown("**Performed Operations:**"))
        for op in self.operations:
            print(op)

# Example usage
mat = [[1, 2, 3], [2, 5, 3], [3, 2, 1]]

m = SymbolicMatrix(mat) # instance of SymbolicMatrix class

# define the same matrix for computation check
original_matrix = sp.Matrix(mat)

**Initial Matrix:**

Matrix([
[1, 2, 3],
[2, 5, 3],
[3, 2, 1]])

In [ ]:
m.add_row(2, 1, -2)

**Operation:** r2 = r2 + -2*r1

Matrix([
[1, 2,  3],
[0, 1, -3],
[3, 2,  1]])

In [ ]:
m.add_row(3, 1, -3)

**Operation:** r3 = r3 + -3*r1

Matrix([
[1,  2,  3],
[0,  1, -3],
[0, -4, -8]])

In [ ]:
m.add_row(3, 2, 4)

**Operation:** r3 = r3 + 4*r2

Matrix([
[1, 2,   3],
[0, 1,  -3],
[0, 0, -20]])

The resulting matrix is an upper triangular matrix.

### Determinant of a Triangular Matrix

For a triangular matrix, the determinant is equal to the product of the elements on its diagonal.

In [ ]:
# The determinant of a triangular matrix is the product of the diagonal elements!
original_matrix.det() == 1 * 1 * (-20)

True

---

## Exercises for Students

Perform row and column operations to reduce the following matrices to an upper triangular form and calculate their determinants by taking the product of the diagonal elements.

1.
$$
A = \begin{bmatrix}
12 & 3 \\
-18 & -4
\end{bmatrix}
$$

2.

$$
B = \begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9
\end{bmatrix}
$$

# Exercises for Students

Perform row and column operations to reduce the following matrices to an **upper triangular form** and calculate their determinants by taking the **product of the diagonal elements**.

## **1. Matrix \( A \):**
\[
A = \begin{bmatrix} 12 & 3 \\ -18 & -4 \end{bmatrix}
\]

### **Solution:**
We apply row operations to convert \( A \) into an upper triangular form.

#### **Step 1: Make the first pivot 1**
Divide \( R_1 \) by 12:

\[
R_1 \rightarrow \frac{1}{12} R_1
\]

\[
A = \begin{bmatrix} 12 & 3 \\ -18 & -4 \end{bmatrix}
\]

#### **Step 2: Eliminate the first column in \( R_2 \)**
Perform the row operation:

\[
R_2 \rightarrow R_2 + \frac{18}{12} R_1 = R_2 + 1.5 R_1
\]

\[
\begin{bmatrix} 12 & 3 \\ 0 & -4 + (1.5 \times 3) \end{bmatrix} = \begin{bmatrix} 12 & 3 \\ 0 & -4 + 4.5 \end{bmatrix} = \begin{bmatrix} 12 & 3 \\ 0 & 0.5 \end{bmatrix}
\]

#### **Step 3: Compute the determinant**
The determinant of an upper triangular matrix is the **product of its diagonal elements**:

\[
\det(A) = 12 \times 0.5 = 6
\]

\[
\boxed{\det(A) = 6}
\]

---

## **2. Matrix \( B \):**
\[
B = \begin{bmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \\ 7 & 8 & 9 \end{bmatrix}
\]

### **Solution:**
We use row operations to convert \( B \) into an upper triangular form.

#### **Step 1: Make the first pivot 1 (already 1)**
We subtract multiples of the first row from the second and third rows.

#### **Step 2: Eliminate column below pivot**
Perform the row operations:

\[
R_2 \rightarrow R_2 - 4R_1, \quad R_3 \rightarrow R_3 - 7R_1
\]

\[
\begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9
\end{bmatrix}
\]

\[
\rightarrow
\begin{bmatrix}
1 & 2 & 3 \\
0 & -3 & -6 \\
0 & -6 & -12
\end{bmatrix}
\]

#### **Step 3: Eliminate next column**
Perform:

\[
R_3 \rightarrow R_3 - 2 R_2
\]

\[
\begin{bmatrix}
1 & 2 & 3 \\
0 & -3 & -6 \\
0 & 0 & 0
\end{bmatrix}
\]

#### **Step 4: Compute the determinant**
Since the third row is all zeros, the determinant is:

\[
\det(B) = 0
\]

\[
\boxed{\det(B) = 0}
\]

---

This Markdown will correctly format in **Jupyter Notebook, GitHub, or MathJax-enabled environments**, showing both the **row operations** and the **determinant calculations** step by step.


In [ ]:
import numpy as np

def row_reduce_to_upper_triangular(matrix):
    """Performs Gaussian elimination to reduce the matrix to upper triangular form."""
    m = matrix.copy()
    n = m.shape[0]
    for i in range(n):
        # Make the pivot element 1 by dividing the row
        if m[i, i] != 0:
            m[i] = m[i] / m[i, i]

        # Eliminate below the pivot
        for j in range(i + 1, n):
            if m[j, i] != 0:
                m[j] -= m[j, i] * m[i]
    return m

def determinant_from_upper_triangular(matrix):
    """Calculates the determinant from an upper triangular matrix."""
    return np.prod(np.diag(matrix))

# Define matrices
A = np.array([[12, 3], [-18, -4]])
B = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Reduce matrices to upper triangular form
upper_triangular_A = row_reduce_to_upper_triangular(A)
upper_triangular_B = row_reduce_to_upper_triangular(B)

# Calculate determinants
det_A = determinant_from_upper_triangular(upper_triangular_A)
det_B = determinant_from_upper_triangular(upper_triangular_B)

# Display results
print("Upper triangular form of A:")
print(upper_triangular_A)
print("Determinant of A:", det_A)

print("\nUpper triangular form of B:")
print(upper_triangular_B)
print("Determinant of B:", det_B)



Upper triangular form of A:
[[1 0]
 [0 1]]
Determinant of A: 1

Upper triangular form of B:
[[1 2 3]
 [0 1 2]
 [0 0 0]]
Determinant of B: 0
